spring:
  application:
    name: gate-keeper
  profiles:
    active: dev

  datasource:
    url: jdbc:oracle:thin:@192.168.140.103:1521:orcl
    username: le
    password: le
    #    ims3d#Prod!#znzz#
    driver-class-name: oracle.jdbc.OracleDriver

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      filters: stat,wall,slf4j,config
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow:
        deny:



netty:
  port: 8079

server:
  port: 8080
